FROM node:20

WORKDIR /app

COPY package.json package-lock.json ./ 

RUN npm install --legacy-peer-deps
RUN npm install @react-native-picker/picker --legacy-peer-deps
RUN npm install @expo/webpack-config --legacy-peer-deps

COPY . .

RUN npx expo export

EXPOSE 3000

CMD ["npx", "serve", "dist"]
